### ISSUE TITLE
Tracking issue: fix deploy doc tests that are in place

### ISSUE THREAD

**Issue by moretea** [microservices-demo/microservices-demo#520]
- [x] [nomad](https://github.com/microservices-demo/microservices-demo/issues/525)
- [x] [docker-compose-weave](https://github.com/microservices-demo/microservices-demo/issues/521)
- [x] [ecs](https://github.com/microservices-demo/microservices-demo/issues/522)
- [x] docker-compose [works properly](https://travis-ci.org/microservices-demo/microservices-demo/builds/189472465)
- [x] [docker-swarm](https://github.com/microservices-demo/microservices-demo/issues/523)
- [x] [kubernetes](https://github.com/microservices-demo/microservices-demo/issues/524)

**Comment by nustiueudinastea** [comment]
This is still not fully fixed. Even though all tests run locally the Travis job still fails. I suspect it's caused by an environment variable.

**Comment by nustiueudinastea** [comment]
All the deploys are working when run manually, while in Travis ECS still fails. I don't consider that related to the deploy docs, but can be caused by the following:
- VM limit in the AWS account
- ECS fails to correctly deploy 3 instances. Instead of deploying 3 VM's it deploy 2, so the cluster never gets in the ready state.
